CREATE TABLE [dbo].[charactertable] (
    [user_id]          INT          IDENTITY (1, 1) NOT NULL,
    [user_name]        VARCHAR (50) NOT NULL,
    [user_age]         VARCHAR (50) NOT NULL,
    [user_gender]      VARCHAR (50) NOT NULL,
    [user_married]     BIT          NOT NULL,
    [user_faceshape]   VARCHAR (50) NOT NULL,
    [user_skincolor]   VARCHAR (50) NOT NULL,
    [user_hairstyle]   VARCHAR (50) NOT NULL,
    [user_haircolor]   VARCHAR (50) NOT NULL,
    [user_eyebrows]    VARCHAR (50) NOT NULL,
    [user_eyeshape]    VARCHAR (50) NOT NULL,
    [user_eyecolor]    VARCHAR (50) NOT NULL,
    [user_liptypes]    VARCHAR (50) NOT NULL,
    [user_lipcolor]    VARCHAR (50) NOT NULL,
    [user_bodytype]    VARCHAR (50) NOT NULL,
    [user_top]         VARCHAR (50) NOT NULL,
    [user_topcolor]    VARCHAR (50) NOT NULL,
    [user_bottom]      VARCHAR (50) NOT NULL,
    [user_bottomcolor] VARCHAR (50) NOT NULL,
    [user_footwear]    VARCHAR (50) NOT NULL,
    [user_accessories] VARCHAR (50) NOT NULL,
    [user_occupation]  VARCHAR (50) NOT NULL,
    [user_timid]       INT          NOT NULL,
    [user_expressive]  INT          NOT NULL,
    [user_cheerful]    INT          NOT NULL,
    [user_calm]        INT          NOT NULL,
    [user_aggressive]  INT          NOT NULL,
    PRIMARY KEY CLUSTERED ([user_id] ASC)
);

